#!/usr/bin/python
#
# File:       ex17
# Author:     Robert Lopez
#
# Started on  Thu Jun 21 15:35:09 2012
# Last update Tue Jul  3 13:03:05 2012 Robert Lopez
#
# Description: ex17a lpthw2e
# Make the script less annoying, more quiet.
#

### The closese I can get to a  "one line" version is cheating:
# from sys import argv; open(argv[1],'w').write(open(argv[2]).read())

from sys import argv
import sys
from os.path import exists

def usage():
    print "Usage: %s <input-filename> <output-filename>" %(sys.argv[0])
    print '''\
This program copies the content of the input-file to the output-file.
Options include:
  --help    : Display this information.
'''
    sys.exit(-2)
    return;

if sys.argv[1].startswith('--'):
    option = sys.argv[1][2:]          # sys.argv[1] without the '--'
    if option == 'help':
        usage()
        sys.exit(-2)
    else:
        print '\nUnknown option, --%s.\n' % (option)
        usage()
        sys.exit(-2)

if len(sys.argv) != 3: 
    usage()
    sys.exit(-2)


script, from_file, to_file = argv

# we could do these two on one line too, how?
input = open(from_file)
indata = input.read()

output = open(to_file, 'w')
output.write(indata)

output.close()
input.close()
