#!/usr/bin/python
#
# File:       ex23
# Author:     Robert Lopez
#
# Started on  Fri Jul 06 17:43:08 2012
# Last update Fri Jul  6 17:43:38 2012 Robert Lopez
#
# Description: ex23 lpthw2e
#

# Find and read code.  Read google api code modules.
